name: Generate Images with Gemini

on:
  workflow_dispatch:

jobs:
  generate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai==0.1.0 Pillow

    - name: Run script
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py
        ls -la

    - name: List generated images
      run: |
        echo "================================================================="
        echo "GENERATED IMAGES:"
        echo "================================================================="
        if [ -d turtle_images ]; then
          echo "Images in turtle_images directory:"
          ls -la turtle_images/
        else
          echo "No turtle_images directory found."
        fi
        
        if [ -f output_image.png ]; then
          echo "\nLatest image was generated: output_image.png"
        else
          echo "\nNo output_image.png found."
        fi
        
        if [ -f output_story.txt ]; then
          echo "\nStory text was generated. First few lines:"
          head -n 5 output_story.txt
          echo "...(truncated)"
        else
          echo "\nNo output_story.txt found."
        fi
        echo "================================================================="

    - name: Provide instructions for manual setup
      run: |
        echo "================================================================="
        echo "INSTRUCTIONS FOR LOCAL SETUP:"
        echo "================================================================="
        echo "To run this locally and save images to your computer:"
        echo ""
        echo "1. Clone the repository:"
        echo "   git clone https://github.com/${{ github.repository }}.git"
        echo ""
        echo "2. Create your .env file with your Gemini API key:"
        echo "   echo 'GEMINI_API_KEY=your_api_key_here' > .env"
        echo ""
        echo "3. Install dependencies:"
        echo "   pip install google-genai==0.1.0 Pillow"
        echo ""
        echo "4. Run the script:"
        echo "   python generate_image.py"
        echo ""
        echo "5. Your images will be in the 'turtle_images' directory"
        echo "================================================================="
