name: Generate Images and Commit to Repository

on:
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai==0.1.0 Pillow

    - name: Run script
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py
        ls -la
        # Create a zip file of all images for easy download
        if [ -d turtle_images ]; then
          zip -r turtle_images.zip turtle_images
          echo "Created turtle_images.zip with all images"
        fi

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Create images branch
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Create and checkout a new branch for the images
        git checkout -b generated-images
        
        # Stage all new images and the story
        git add turtle_images/*.png
        git add output_story.txt
        git add output_image.png
        git add turtle_images.zip || echo "No zip file to add"
        
        # Get current date
        TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        
        # Commit the changes
        git commit -m "Generated turtle images on $TIMESTAMP" || echo "No new images to commit"
        
        # Configure git to use the provided token
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        
        # Push to the branch
        git push -f origin generated-images
        
    - name: Create download instructions
      run: |
        echo "=================================================================" 
        echo "DOWNLOAD LINKS:"
        echo "=================================================================" 
        echo "The images have been committed to the 'generated-images' branch."
        echo ""
        echo "Direct links to download:"
        
        # Generate links to each image
        REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/generated-images"
        
        echo "Story text: $REPO_URL/output_story.txt"
        echo ""
        
        echo "Individual images:"
        for img in turtle_images/*.png; do
          IMG_NAME=$(basename "$img")
          echo "- $IMG_NAME: $REPO_URL/turtle_images/$IMG_NAME"
        done
        
        echo ""
        echo "All images as ZIP: $REPO_URL/turtle_images.zip"
        echo ""
        echo "You can also browse all files at:"
        echo "https://github.com/${{ github.repository }}/tree/generated-images"
        echo "=================================================================" 

    # Fallback: Also upload as artifacts in case push fails
    - name: Upload turtle images
      uses: actions/upload-artifact@v2
      with:
        name: turtle-images
        path: turtle_images/
        retention-days: 90
        
    - name: Upload story text
      uses: actions/upload-artifact@v2
      with:
        name: turtle-story
        path: output_story.txt
        retention-days: 90
        
    - name: Upload zipped images
      uses: actions/upload-artifact@v2
      with:
        name: all-turtle-images-zip
        path: turtle_images.zip
        retention-days: 90
        if-no-files-found: ignore
