name: Generate Images with Gemini

on:
  workflow_dispatch:

jobs:
  generate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai Pillow

    - name: Run image generation
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py

    - name: Upload image artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: generated-image
        path: output_image.png
