name: Generate Images and Commit to Repository

on:
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai==0.1.0 Pillow

    - name: Run script
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py
        ls -la
        # Create a zip file of all images for easy download
        if [ -d turtle_images ]; then
          zip -r turtle_images.zip turtle_images
          echo "Created turtle_images.zip with all images"
        fi

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Create images branch
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Create and checkout a new branch for the images
        git checkout -b generated-images
        
        # Stage all new images and the story
        git add turtle_images/*.png
        git add output_story.txt
        git add output_image.png
        git add turtle_images.zip || echo "No zip file to add"
        
        # Get current date
        TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
        
        # Commit the changes
        git commit -m "Generated turtle images on $TIMESTAMP" || echo "No new images to commit"
        
        # Configure git to use the provided token
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        
        # Push to the branch
        git push -f origin generated-images
        
    - name: Create HTML index for images
      run: |
        # Create a simple HTML file to view the images
        cat > image_viewer.html << EOL
        <!DOCTYPE html>
        <html>
        <head>
            <title>Gemini Generated Turtle Images</title>
            <style>
                body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
                h1 { color: #2a7ae2; }
                .image-container { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 30px; }
                .image-card { border: 1px solid #ddd; border-radius: 8px; overflow: hidden; width: 45%; max-width: 500px; margin-bottom: 20px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
                .image-card img { width: 100%; height: auto; display: block; }
                .image-card .caption { padding: 15px; background-color: #f8f9fa; }
                .story { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin-top: 30px; line-height: 1.6; }
                pre { white-space: pre-wrap; }
            </style>
        </head>
        <body>
            <h1>Gemini Generated Turtle Images</h1>
            <p>These images were generated using the Google Gemini AI API on $(date).</p>
            
            <div class="story">
                <h2>The Turtle Story</h2>
                <pre id="story-content">$(cat output_story.txt)</pre>
            </div>
            
            <h2>Images</h2>
            <div class="image-container">
        EOL
        
        # Add each image to the HTML
        for i in $(ls turtle_images/*.png | sort); do
          IMG_NAME=$(basename "$i")
          SCENE_NUM=$(echo $IMG_NAME | sed 's/image_\([0-9]*\).png/\1/')
          echo "                <div class=\"image-card\">" >> image_viewer.html
          echo "                    <img src=\"$i\" alt=\"Turtle Scene $SCENE_NUM\">" >> image_viewer.html
          echo "                    <div class=\"caption\">" >> image_viewer.html
          echo "                        <h3>Scene $SCENE_NUM</h3>" >> image_viewer.html
          echo "                    </div>" >> image_viewer.html
          echo "                </div>" >> image_viewer.html
        done
        
        # Close the HTML
        cat >> image_viewer.html << EOL
            </div>
            
            <p><a href="turtle_images.zip">Download all images as ZIP</a></p>
        </body>
        </html>
        EOL
        
        # Add the HTML viewer to git
        git add image_viewer.html
        git commit -m "Add HTML image viewer" || echo "No changes to commit"
        git push origin generated-images
        
    - name: Create download instructions
      run: |
        echo "=================================================================" 
        echo "DOWNLOAD LINKS:"
        echo "=================================================================" 
        echo "The images have been committed to the 'generated-images' branch."
        echo ""
        echo "Direct links to download:"
        
        # Generate links to each image
        REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/generated-images"
        
        echo "Story text: $REPO_URL/output_story.txt"
        echo ""
        
        echo "Individual images:"
        for img in turtle_images/*.png; do
          IMG_NAME=$(basename "$img")
          echo "- $IMG_NAME: $REPO_URL/turtle_images/$IMG_NAME"
        done
        
        echo ""
        echo "All images as ZIP: $REPO_URL/turtle_images.zip"
        echo ""
        echo "HTML Image Viewer: $REPO_URL/image_viewer.html"
        echo ""
        echo "You can also browse all files at:"
        echo "https://github.com/${{ github.repository }}/tree/generated-images"
        echo "=================================================================" 
