name: Generate Images with Gemini

on:
  workflow_dispatch:

jobs:
  generate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai==0.1.0 Pillow

    - name: Run script
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py
        ls -la

    - name: Prepare downloads
      run: |
        # Create a directory for downloads
        mkdir -p download_package
        
        # Copy individual images
        if [ -d turtle_images ]; then
          cp -r turtle_images download_package/
          echo "Added all turtle images to download package"
        fi
        
        # Copy latest image if available
        if [ -f output_image.png ]; then
          cp output_image.png download_package/
          echo "Added latest image to download package"
        fi
        
        # Copy story text
        if [ -f output_story.txt ]; then
          cp output_story.txt download_package/
          echo "Added story to download package"
        fi
        
        # Create a README file with instructions
        echo "# Gemini Generated Turtle Images" > download_package/README.md
        echo "" >> download_package/README.md
        echo "This package contains:" >> download_package/README.md
        echo "- A story about a baby turtle generated by Gemini AI" >> download_package/README.md
        echo "- Images for each scene in the story" >> download_package/README.md
        echo "" >> download_package/README.md
        echo "Generated on: $(date)" >> download_package/README.md
        
        # List the contents for verification
        echo "\nContents prepared for download:"
        ls -la download_package

    - name: Upload images as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gemini-turtle-story-package
        path: download_package
        retention-days: 7

    - name: Create an output file with image URLs
      run: |
        echo "================================================================="  > image_locations.txt
        echo "IMAGE DOWNLOAD INSTRUCTIONS:" >> image_locations.txt
        echo "================================================================="  >> image_locations.txt
        echo "1. In GitHub: Go to Actions tab → this workflow run → Artifacts → download zip" >> image_locations.txt
        echo "2. Direct URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> image_locations.txt
        echo "" >> image_locations.txt
        echo "All generated images are stored in the 'turtle_images' directory" >> image_locations.txt
        echo "================================================================="  >> image_locations.txt
        cat image_locations.txt

    - name: Provide download instructions
      run: |
        echo "=================================================================="
        echo "DOWNLOAD INSTRUCTIONS:"
        echo "=================================================================="
        echo "1. Go to the Actions tab in your GitHub repository"
        echo "2. Click on this workflow run"
        echo "3. Scroll to the bottom and find 'Artifacts'"
        echo "4. Click on 'gemini-turtle-story-package' to download the zip file"
        echo "5. Extract the zip file on your local computer"
        echo "=================================================================="
