name: Generate Images with Gemini

on:
  workflow_dispatch:

jobs:
  generate_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-genai==0.1.0 Pillow
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

    - name: Run script
      env:
        GEMINI_API_KEY: "AIzaSyC8FuTNC3FxLs0Qx2ciRoLwxjOrLGqOB5A"
      run: |
        python generate_image.py
        ls -la

    - name: Upload to Google Drive
      run: |
        python upload_to_drive.py
        cat drive_links.txt || echo "No drive links file found"

    - name: Create output folder and copy files
      run: |
        mkdir -p ../output_folder
        # Copy individual images
        if [ -d turtle_images ]; then
          cp -r turtle_images ../output_folder/
          echo "All turtle images copied to output folder"
        fi
        # Copy latest image if available
        if [ -f output_image.png ]; then
          cp output_image.png ../output_folder/
          echo "Latest image copied to output folder"
        fi
        # Copy story text
        if [ -f output_story.txt ]; then
          cp output_story.txt ../output_folder/
          echo "Story copied to output folder"
        fi
        # Copy drive links file if available
        if [ -f drive_links.txt ]; then
          cp drive_links.txt ../output_folder/
          echo "Drive links copied to output folder"
        fi
